// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnNMaEb2-eJQC4NtoqDlfQCXmJsO3Bif4',
    appId: '1:713234690817:web:adb58003494913fd7ae100',
    messagingSenderId: '713234690817',
    projectId: 'experience-app-ca275',
    authDomain: 'experience-app-ca275.firebaseapp.com',
    storageBucket: 'experience-app-ca275.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqNd71amN5f8sZP1A22tF5LXl-VatC_40',
    appId: '1:713234690817:android:786b2098813b47407ae100',
    messagingSenderId: '713234690817',
    projectId: 'experience-app-ca275',
    storageBucket: 'experience-app-ca275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5CdL0v3DVB3jDJtlWu_nC5Jd-QA3fFc0',
    appId: '1:713234690817:ios:09c56e17d878a73a7ae100',
    messagingSenderId: '713234690817',
    projectId: 'experience-app-ca275',
    storageBucket: 'experience-app-ca275.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5CdL0v3DVB3jDJtlWu_nC5Jd-QA3fFc0',
    appId: '1:713234690817:ios:09c56e17d878a73a7ae100',
    messagingSenderId: '713234690817',
    projectId: 'experience-app-ca275',
    storageBucket: 'experience-app-ca275.firebasestorage.app',
    iosBundleId: 'com.example.experienceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnNMaEb2-eJQC4NtoqDlfQCXmJsO3Bif4',
    appId: '1:713234690817:web:748a1535647aa3bf7ae100',
    messagingSenderId: '713234690817',
    projectId: 'experience-app-ca275',
    authDomain: 'experience-app-ca275.firebaseapp.com',
    storageBucket: 'experience-app-ca275.firebasestorage.app',
  );
}
